### PR TITLE
TDD, Port, Kalman, Telemetry, and Cleanup

### PR DESCRIPTION
**Pull request by soderstroff**
1) Added a Technical Design Document for anyone not already associated and familiar with the project.
2) Ported old cpp files to C and made changes where necessary. I have not changed any calls to Serial as I do not know what the serial port is on our board (I think these should be changed to telemetry calls, anyway).
3) The Kalman filter is essentially finished, minus scheduling. kalman.c/h written, integrators added to sensors.c. typedefs for INS and GPS/Mag data written (separating the two was more convenient). Algorithms written. TODO: I need to write a numpy script to automatically generate our kalman gain matrix.
4) Added event handlers for the subsystems. Current supported keys: "setKalman", "setKalmanRow", "setHeadingPID", "setVelocityPID", and "setMap". Planned RPC keys: "Stop", "Start", "getLog", and general getters for all the currently implemented getters. 
5) There was general code cleanup. Stylistic changes (switched to K&R style, not snowplow), renamed some things, changed alignment, but I also made semantic changes, like turning the map into a linked list, and opting for arrays instead of structs for a lot of the data passing.

Comments extremely welcome.

### CODE REVIEW

**Comment by jamesdsmith** [comment]
TDD looks pretty good
The build is pretty messed up though, side effects of the port from Arduino. If there are features you don't know how to port, or aren't worth porting (the entire motion.c file), just preprocessor it out and include a list of preprocessor tags that we need to resolve before we can consider the port complete.

**Comment by jamesdsmith** [comment]
Also please do not create preprocessor macros for things like for loop headers... there isn't any reason to be doing that.
Make sure you are compiling your code with the TI toolchain. They are not using standard GCC.

**Comment by jamesdsmith** [comment]
The change to nav data (into an enum/array) is kind of convoluted, is there a particular reason for that change? If it is a matter of it working better for the filtering code, I would leave navData as a struct and build your own internal data structure for filtering on the other side of the data transfer

**Comment by soderstroff** [comment]
Besides everything I already mentioned (I didn't see any of these comments this morning, sorry), I'm going to go through and at least have it build correctly on code composer with function stubs and macros. I'll remove the loop initializer macro.

The array code is vastly easier to work with because you can loop over an array and not a struct, and the enum was to keep access to fields by name. The struct is probably a better approach, though. I didn't want to copy all of the data being passed around into my own data structure (which would have the same memory representation anyway sans alignment) but in retrospect perhaps copying ~15 floats isn't worth that kind of scrutiny.

**Pull request merged**
